includes:
  - base.yaml
targets:
  - target: /bin
    createlinks:
      - src: /opt/python-occlum/bin/python3
        linkname: python3
  # python packages
  - target: /opt
    copy:
      - dirs:
          - ../python-occlum

  # below are python code and data
  - target: /data
    copy:
      - dirs:
          - ../data
  # below are python code and data
#  - target: /
#    copy:
#      - files:
#        - ../main.py

  - target: /
    copy:
      - dirs:
        - ../src

  # Optional: Uncomment and add your cert/key files if needed
  # - target: /etc
  #   copy:
  #     - files:
  #       - ../your_cert.crt
  #       - ../your_key.key